import { freshCard } from './srs'
import type { VocabCard } from '../types'

export const VOCAB_SEEDS: Record<string, VocabCard[]> = {
  begruessungen: [
    { id: 'begr-1', word: 'Hallo', translation: 'Hello', pronunciation: 'HAH-lo', example: 'Hallo, wie geht es dir?', deck: 'begruessungen', ...freshCard() },
    { id: 'begr-2', word: 'Guten Morgen', translation: 'Good morning', pronunciation: 'GOO-ten', deck: 'begruessungen', ...freshCard() },
    { id: 'begr-3', word: 'Wie geht es dir?', translation: 'How are you?', pronunciation: 'VEE gayt', deck: 'begruessungen', ...freshCard() },
    { id: 'begr-4', word: 'Danke', translation: 'Thank you', pronunciation: 'DAHN-kuh', deck: 'begruessungen', ...freshCard() },
    { id: 'begr-5', word: 'Bitte', translation: 'Please', pronunciation: 'BIT-uh', deck: 'begruessungen', ...freshCard() },
    { id: 'begr-6', word: 'Auf Wiedersehen', translation: 'Goodbye', pronunciation: 'owf VEE-der', deck: 'begruessungen', ...freshCard() },
    { id: 'begr-7', word: 'Ja', translation: 'Yes', pronunciation: 'YAH', deck: 'begruessungen', ...freshCard() },
    { id: 'begr-8', word: 'Nein', translation: 'No', pronunciation: 'NINE', deck: 'begruessungen', ...freshCard() },
    { id: 'begr-9', word: 'Entschuldigung', translation: 'Sorry', pronunciation: 'ent-SHOOL', deck: 'begruessungen', ...freshCard() },
    { id: 'begr-10', word: 'Wie heißt du?', translation: 'What is your name?', pronunciation: 'VEE HYST', deck: 'begruessungen', ...freshCard() },
    { id: 'begr-11', word: 'Ich heiße Anna', translation: 'My name is Anna', pronunciation: 'ikh HYST', deck: 'begruessungen', ...freshCard() },
    { id: 'begr-12', word: 'Schön dich zu treffen', translation: 'Nice to meet you', pronunciation: 'SHHORN', deck: 'begruessungen', ...freshCard() },
    { id: 'begr-13', word: 'Gute Nacht', translation: 'Good night', pronunciation: 'GOO-tuh', deck: 'begruessungen', ...freshCard() },
    { id: 'begr-14', word: 'Bis bald', translation: 'See you soon', pronunciation: 'bis BAHLT', deck: 'begruessungen', ...freshCard() },
    { id: 'begr-15', word: 'Viel Erfolg', translation: 'Good luck', pronunciation: 'feel er-FOLK', deck: 'begruessungen', ...freshCard() },
    { id: 'begr-16', word: 'Guten Appetit', translation: 'Enjoy your meal', pronunciation: 'GOO-ten', deck: 'begruessungen', ...freshCard() },
    { id: 'begr-17', word: 'Prost', translation: 'Cheers', pronunciation: 'PROST', deck: 'begruessungen', ...freshCard() },
    { id: 'begr-18', word: 'Tschüss', translation: 'Bye', pronunciation: 'CHOOS', deck: 'begruessungen', ...freshCard() },
    { id: 'begr-19', word: 'Alles Gute', translation: 'All the best', pronunciation: 'AHL-es', deck: 'begruessungen', ...freshCard() },
    { id: 'begr-20', word: 'Guten Tag', translation: 'Good day', pronunciation: 'GOO-ten TAHG', deck: 'begruessungen', ...freshCard() },
  ],
  zahlen: [
    { id: 'zahl-1', word: 'Null', translation: 'Zero', pronunciation: 'NOOL', deck: 'zahlen', ...freshCard() },
    { id: 'zahl-2', word: 'Eins', translation: 'One', pronunciation: 'INES', deck: 'zahlen', ...freshCard() },
    { id: 'zahl-3', word: 'Zwei', translation: 'Two', pronunciation: 'TSVYE', deck: 'zahlen', ...freshCard() },
    { id: 'zahl-4', word: 'Drei', translation: 'Three', pronunciation: 'DRYE', deck: 'zahlen', ...freshCard() },
    { id: 'zahl-5', word: 'Vier', translation: 'Four', pronunciation: 'FEER', deck: 'zahlen', ...freshCard() },
    { id: 'zahl-6', word: 'Fünf', translation: 'Five', pronunciation: 'FOONF', deck: 'zahlen', ...freshCard() },
    { id: 'zahl-7', word: 'Sechs', translation: 'Six', pronunciation: 'ZECHS', deck: 'zahlen', ...freshCard() },
    { id: 'zahl-8', word: 'Sieben', translation: 'Seven', pronunciation: 'ZEE-ben', deck: 'zahlen', ...freshCard() },
    { id: 'zahl-9', word: 'Acht', translation: 'Eight', pronunciation: 'AHKT', deck: 'zahlen', ...freshCard() },
    { id: 'zahl-10', word: 'Neun', translation: 'Nine', pronunciation: 'NOYN', deck: 'zahlen', ...freshCard() },
    { id: 'zahl-11', word: 'Zehn', translation: 'Ten', pronunciation: 'TSEHN', deck: 'zahlen', ...freshCard() },
    { id: 'zahl-12', word: 'Elf', translation: 'Eleven', pronunciation: 'ELF', deck: 'zahlen', ...freshCard() },
    { id: 'zahl-13', word: 'Zwölf', translation: 'Twelve', pronunciation: 'TSVOLF', deck: 'zahlen', ...freshCard() },
    { id: 'zahl-14', word: 'Zwanzig', translation: 'Twenty', pronunciation: 'TSVAHN', deck: 'zahlen', ...freshCard() },
    { id: 'zahl-15', word: 'Dreißig', translation: 'Thirty', pronunciation: 'DRYSE', deck: 'zahlen', ...freshCard() },
    { id: 'zahl-16', word: 'Vierzig', translation: 'Forty', pronunciation: 'FEER-tsik', deck: 'zahlen', ...freshCard() },
    { id: 'zahl-17', word: 'Fünfzig', translation: 'Fifty', pronunciation: 'FOONF-tsik', deck: 'zahlen', ...freshCard() },
    { id: 'zahl-18', word: 'Hundert', translation: 'Hundred', pronunciation: 'HOON-dert', deck: 'zahlen', ...freshCard() },
    { id: 'zahl-19', word: 'Tausend', translation: 'Thousand', pronunciation: 'TOW-zent', deck: 'zahlen', ...freshCard() },
    { id: 'zahl-20', word: 'Million', translation: 'Million', pronunciation: 'mil-ee-OHN', deck: 'zahlen', ...freshCard() },
  ],
  essen: [
    { id: 'essen-1', word: 'Apfel', translation: 'Apple', pronunciation: 'AHP-fell', deck: 'essen', ...freshCard() },
    { id: 'essen-2', word: 'Banane', translation: 'Banana', pronunciation: 'bah-NAH', deck: 'essen', ...freshCard() },
    { id: 'essen-3', word: 'Brot', translation: 'Bread', pronunciation: 'BROHT', deck: 'essen', ...freshCard() },
    { id: 'essen-4', word: 'Käse', translation: 'Cheese', pronunciation: 'KAY-zuh', deck: 'essen', ...freshCard() },
    { id: 'essen-5', word: 'Milch', translation: 'Milk', pronunciation: 'MILKH', deck: 'essen', ...freshCard() },
    { id: 'essen-6', word: 'Ei', translation: 'Egg', pronunciation: 'EYE', deck: 'essen', ...freshCard() },
    { id: 'essen-7', word: 'Fleisch', translation: 'Meat', pronunciation: 'FLYSH', deck: 'essen', ...freshCard() },
    { id: 'essen-8', word: 'Fisch', translation: 'Fish', pronunciation: 'FISH', deck: 'essen', ...freshCard() },
    { id: 'essen-9', word: 'Huhn', translation: 'Chicken', pronunciation: 'HOON', deck: 'essen', ...freshCard() },
    { id: 'essen-10', word: 'Wasser', translation: 'Water', pronunciation: 'VAHS-ser', deck: 'essen', ...freshCard() },
    { id: 'essen-11', word: 'Kaffee', translation: 'Coffee', pronunciation: 'kah-FAY', deck: 'essen', ...freshCard() },
    { id: 'essen-12', word: 'Tee', translation: 'Tea', pronunciation: 'TAY', deck: 'essen', ...freshCard() },
    { id: 'essen-13', word: 'Zucker', translation: 'Sugar', pronunciation: 'TSOO-ker', deck: 'essen', ...freshCard() },
    { id: 'essen-14', word: 'Salz', translation: 'Salt', pronunciation: 'ZAHLTS', deck: 'essen', ...freshCard() },
    { id: 'essen-15', word: 'Pfeffer', translation: 'Pepper', pronunciation: 'PFEFF-er', deck: 'essen', ...freshCard() },
    { id: 'essen-16', word: 'Gemüse', translation: 'Vegetable', pronunciation: 'guh-MOO', deck: 'essen', ...freshCard() },
    { id: 'essen-17', word: 'Kartoffel', translation: 'Potato', pronunciation: 'kar-TOFF', deck: 'essen', ...freshCard() },
    { id: 'essen-18', word: 'Tomate', translation: 'Tomato', pronunciation: 'to-MAH', deck: 'essen', ...freshCard() },
    { id: 'essen-19', word: 'Salat', translation: 'Salad', pronunciation: 'zah-LAHT', deck: 'essen', ...freshCard() },
    { id: 'essen-20', word: 'Dessert', translation: 'Dessert', pronunciation: 'des-AIR', deck: 'essen', ...freshCard() },
    { id: 'essen-21', word: 'Obst', translation: 'Fruit', pronunciation: 'OHPST', deck: 'essen', ...freshCard() },
    { id: 'essen-22', word: 'Fleischbrühe', translation: 'Broth', pronunciation: 'FLYSH', deck: 'essen', ...freshCard() },
    { id: 'essen-23', word: 'Suppenteller', translation: 'Soup bowl', pronunciation: 'ZOO-pen', deck: 'essen', ...freshCard() },
    { id: 'essen-24', word: 'Gabel', translation: 'Fork', pronunciation: 'GAH-bel', deck: 'essen', ...freshCard() },
    { id: 'essen-25', word: 'Messer', translation: 'Knife', pronunciation: 'MESS-er', deck: 'essen', ...freshCard() },
    { id: 'essen-26', word: 'Löffel', translation: 'Spoon', pronunciation: 'LOF-el', deck: 'essen', ...freshCard() },
    { id: 'essen-27', word: 'Teller', translation: 'Plate', pronunciation: 'TELL-er', deck: 'essen', ...freshCard() },
    { id: 'essen-28', word: 'Glas', translation: 'Glass', pronunciation: 'GLAHS', deck: 'essen', ...freshCard() },
    { id: 'essen-29', word: 'Tasse', translation: 'Cup', pronunciation: 'TAHS-uh', deck: 'essen', ...freshCard() },
    { id: 'essen-30', word: 'Restaurant', translation: 'Restaurant', pronunciation: 'rest-o-RAHN', deck: 'essen', ...freshCard() },
    { id: 'essen-31', word: 'Kellner', translation: 'Waiter', pronunciation: 'KELL-ner', deck: 'essen', ...freshCard() },
    { id: 'essen-32', word: 'Speisekarte', translation: 'Menu', pronunciation: 'SHPY-zuh', deck: 'essen', ...freshCard() },
    { id: 'essen-33', word: 'Rechnung', translation: 'Bill', pronunciation: 'REKH-nung', deck: 'essen', ...freshCard() },
    { id: 'essen-34', word: 'Trinkgeld', translation: 'Tip', pronunciation: 'TRINK-gelt', deck: 'essen', ...freshCard() },
    { id: 'essen-35', word: 'Knoblauch', translation: 'Garlic', pronunciation: 'KNOB-lowkh', deck: 'essen', ...freshCard() },
    { id: 'essen-36', word: 'Zwiebel', translation: 'Onion', pronunciation: 'TSVEE-bel', deck: 'essen', ...freshCard() },
    { id: 'essen-37', word: 'Paprika', translation: 'Paprika', pronunciation: 'pah-PREE-kah', deck: 'essen', ...freshCard() },
    { id: 'essen-38', word: 'Öl', translation: 'Oil', pronunciation: 'OL', deck: 'essen', ...freshCard() },
    { id: 'essen-39', word: 'Essig', translation: 'Vinegar', pronunciation: 'ES-sik', deck: 'essen', ...freshCard() },
    { id: 'essen-40', word: 'Butter', translation: 'Butter', pronunciation: 'BOOT-er', deck: 'essen', ...freshCard() },
  ],
  reisen: [
    { id: 'reisen-1', word: 'Flughafen', translation: 'Airport', pronunciation: 'FLOCK-hah', deck: 'reisen', ...freshCard() },
    { id: 'reisen-2', word: 'Bahnhof', translation: 'Train Station', pronunciation: 'BAHN-hoff', deck: 'reisen', ...freshCard() },
    { id: 'reisen-3', word: 'Hotel', translation: 'Hotel', pronunciation: 'ho-TEL', deck: 'reisen', ...freshCard() },
    { id: 'reisen-4', word: 'Gepäck', translation: 'Luggage', pronunciation: 'guh-PECK', deck: 'reisen', ...freshCard() },
    { id: 'reisen-5', word: 'Ticket', translation: 'Ticket', pronunciation: 'TIK-et', deck: 'reisen', ...freshCard() },
    { id: 'reisen-6', word: 'Karte', translation: 'Map', pronunciation: 'KAR-tuh', deck: 'reisen', ...freshCard() },
    { id: 'reisen-7', word: 'Visum', translation: 'Visa', pronunciation: 'VEE-zoom', deck: 'reisen', ...freshCard() },
    { id: 'reisen-8', word: 'Reisebüro', translation: 'Travel Agency', pronunciation: 'RYE-zuh', deck: 'reisen', ...freshCard() },
    { id: 'reisen-9', word: 'Flugticket', translation: 'Flight Ticket', pronunciation: 'FLOCK-TIK', deck: 'reisen', ...freshCard() },
    { id: 'reisen-10', word: 'Sitzplatz', translation: 'Seat', pronunciation: 'ZITS-plahts', deck: 'reisen', ...freshCard() },
    { id: 'reisen-11', word: 'Pilot', translation: 'Pilot', pronunciation: 'pee-LOT', deck: 'reisen', ...freshCard() },
    { id: 'reisen-12', word: 'Zoll', translation: 'Customs', pronunciation: 'TSOL', deck: 'reisen', ...freshCard() },
    { id: 'reisen-13', word: 'Geldautomat', translation: 'ATM', pronunciation: 'GELT-ow', deck: 'reisen', ...freshCard() },
    { id: 'reisen-14', word: 'Wechselkurs', translation: 'Exchange Rate', pronunciation: 'VECK-sel', deck: 'reisen', ...freshCard() },
    { id: 'reisen-15', word: 'Versicherung', translation: 'Insurance', pronunciation: 'fer-ZIKK', deck: 'reisen', ...freshCard() },
    { id: 'reisen-16', word: 'Koffer', translation: 'Suitcase', pronunciation: 'KOFF-er', deck: 'reisen', ...freshCard() },
    { id: 'reisen-17', word: 'Rucksack', translation: 'Backpack', pronunciation: 'ROOK-zahk', deck: 'reisen', ...freshCard() },
    { id: 'reisen-18', word: 'Museum', translation: 'Museum', pronunciation: 'moo-ZAY', deck: 'reisen', ...freshCard() },
    { id: 'reisen-19', word: 'Strand', translation: 'Beach', pronunciation: 'SHTRANDT', deck: 'reisen', ...freshCard() },
    { id: 'reisen-20', word: 'Berg', translation: 'Mountain', pronunciation: 'BERK', deck: 'reisen', ...freshCard() },
    { id: 'reisen-21', word: 'See', translation: 'Lake', pronunciation: 'ZAY', deck: 'reisen', ...freshCard() },
    { id: 'reisen-22', word: 'Fluss', translation: 'River', pronunciation: 'FLOOS', deck: 'reisen', ...freshCard() },
    { id: 'reisen-23', word: 'Wald', translation: 'Forest', pronunciation: 'VAHLT', deck: 'reisen', ...freshCard() },
    { id: 'reisen-24', word: 'Stadt', translation: 'City', pronunciation: 'SHTAHT', deck: 'reisen', ...freshCard() },
    { id: 'reisen-25', word: 'Land', translation: 'Country', pronunciation: 'LAHNT', deck: 'reisen', ...freshCard() },
    { id: 'reisen-26', word: 'Sehenswürdigkeit', translation: 'Attraction', pronunciation: 'ZAY-ens', deck: 'reisen', ...freshCard() },
    { id: 'reisen-27', word: 'Kirche', translation: 'Church', pronunciation: 'KEER-khuh', deck: 'reisen', ...freshCard() },
    { id: 'reisen-28', word: 'Schloss', translation: 'Castle', pronunciation: 'SHLOS', deck: 'reisen', ...freshCard() },
    { id: 'reisen-29', word: 'Park', translation: 'Park', pronunciation: 'PARK', deck: 'reisen', ...freshCard() },
    { id: 'reisen-30', word: 'Brunnen', translation: 'Fountain', pronunciation: 'BROO-nen', deck: 'reisen', ...freshCard() },
    { id: 'reisen-31', word: 'Platz', translation: 'Square', pronunciation: 'PLAHTS', deck: 'reisen', ...freshCard() },
    { id: 'reisen-32', word: 'Straße', translation: 'Street', pronunciation: 'SHTRAHS', deck: 'reisen', ...freshCard() },
    { id: 'reisen-33', word: 'Weg', translation: 'Path', pronunciation: 'VAYK', deck: 'reisen', ...freshCard() },
    { id: 'reisen-34', word: 'Route', translation: 'Route', pronunciation: 'ROO-tuh', deck: 'reisen', ...freshCard() },
    { id: 'reisen-35', word: 'Ausflug', translation: 'Excursion', pronunciation: 'OWS-flock', deck: 'reisen', ...freshCard() },
  ],
  arbeit: [
    { id: 'arbeit-1', word: 'Büro', translation: 'Office', pronunciation: 'BEW-roh', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-2', word: 'Schreibtisch', translation: 'Desk', pronunciation: 'SHRYP', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-3', word: 'Computer', translation: 'Computer', pronunciation: 'kom-POO', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-4', word: 'Sitzung', translation: 'Meeting', pronunciation: 'ZIT-sung', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-5', word: 'Projekt', translation: 'Project', pronunciation: 'pro-YEKT', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-6', word: 'Deadline', translation: 'Deadline', pronunciation: 'DEAD-line', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-7', word: 'Besprechung', translation: 'Discussion', pronunciation: 'buh-SHPREKK', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-8', word: 'Kollege', translation: 'Colleague', pronunciation: 'kol-LAY', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-9', word: 'Chef', translation: 'Boss', pronunciation: 'SHEF', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-10', word: 'Gehalt', translation: 'Salary', pronunciation: 'guh-HALT', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-11', word: 'Bonus', translation: 'Bonus', pronunciation: 'BOH-nus', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-12', word: 'Beförderung', translation: 'Promotion', pronunciation: 'buh-FOR', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-13', word: 'Fähigkeiten', translation: 'Skills', pronunciation: 'FAY-ik', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-14', word: 'Erfahrung', translation: 'Experience', pronunciation: 'er-FAH', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-15', word: 'Lebenslauf', translation: 'CV', pronunciation: 'LAY-bens', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-16', word: 'Bewerbung', translation: 'Application', pronunciation: 'buh-VER', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-17', word: 'Interview', translation: 'Interview', pronunciation: 'in-ter-VOO', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-18', word: 'Kündigung', translation: 'Resignation', pronunciation: 'KUN-dee', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-19', word: 'Urlaub', translation: 'Vacation', pronunciation: 'OOR-lowp', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-20', word: 'Arbeitsvertrag', translation: 'Contract', pronunciation: 'AHR-bites', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-21', word: 'E-Mail', translation: 'Email', pronunciation: 'EE-mail', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-22', word: 'Telefonkonferenz', translation: 'Conference call', pronunciation: 'tuh-LAY', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-23', word: 'Konferenzraum', translation: 'Conference room', pronunciation: 'kon-fer-ENTS', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-24', word: 'Whiteboard', translation: 'Whiteboard', pronunciation: 'HWITE-bord', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-25', word: 'Präsentation', translation: 'Presentation', pronunciation: 'pray-zen-TAH', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-26', word: 'Bericht', translation: 'Report', pronunciation: 'buh-RIKT', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-27', word: 'Datei', translation: 'File', pronunciation: 'dah-TAY', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-28', word: 'Ordner', translation: 'Folder', pronunciation: 'ORD-ner', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-29', word: 'Dokument', translation: 'Document', pronunciation: 'dok-oo-MENT', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-30', word: 'Vertrag', translation: 'Agreement', pronunciation: 'fer-TRAHK', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-31', word: 'Unterschrift', translation: 'Signature', pronunciation: 'OON-ter-shrift', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-32', word: 'Genehmigung', translation: 'Approval', pronunciation: 'guh-NAY-mee', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-33', word: 'Abgabetermin', translation: 'Deadline', pronunciation: 'AHP-gah', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-34', word: 'Fortschritt', translation: 'Progress', pronunciation: 'FORT-shritt', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-35', word: 'Erfolg', translation: 'Success', pronunciation: 'er-FOLK', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-36', word: 'Problem', translation: 'Problem', pronunciation: 'PROB-lem', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-37', word: 'Lösung', translation: 'Solution', pronunciation: 'LOH-sung', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-38', word: 'Team', translation: 'Team', pronunciation: 'TEAM', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-39', word: 'Mitarbeiter', translation: 'Employee', pronunciation: 'MIT-ar-by', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-40', word: 'Geschäftsführer', translation: 'CEO', pronunciation: 'guh-SHEFTS', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-41', word: 'Abteilung', translation: 'Department', pronunciation: 'AHP-ty-lung', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-42', word: 'Schicht', translation: 'Shift', pronunciation: 'SHIKT', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-43', word: 'Pause', translation: 'Break', pronunciation: 'POW-zuh', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-44', word: 'Überstunden', translation: 'Overtime', pronunciation: 'OO-ber-shun', deck: 'arbeit', ...freshCard() },
    { id: 'arbeit-45', word: 'Weiterbildung', translation: 'Training', pronunciation: 'VY-ter-bild', deck: 'arbeit', ...freshCard() },
  ],
  sport: [
    { id: 'sport-1', word: 'Fußball', translation: 'Soccer', pronunciation: 'FOOS-bahl', deck: 'sport', ...freshCard() },
    { id: 'sport-2', word: 'Volleyball', translation: 'Volleyball', pronunciation: 'VOL-ey', deck: 'sport', ...freshCard() },
    { id: 'sport-3', word: 'Tennis', translation: 'Tennis', pronunciation: 'TEN-is', deck: 'sport', ...freshCard() },
    { id: 'sport-4', word: 'Laufen', translation: 'Running', pronunciation: 'LOW-fen', deck: 'sport', ...freshCard() },
    { id: 'sport-5', word: 'Schwimmen', translation: 'Swimming', pronunciation: 'SHVIM-en', deck: 'sport', ...freshCard() },
    { id: 'sport-6', word: 'Radfahren', translation: 'Cycling', pronunciation: 'RAHT-fah', deck: 'sport', ...freshCard() },
    { id: 'sport-7', word: 'Yoga', translation: 'Yoga', pronunciation: 'YOH-gah', deck: 'sport', ...freshCard() },
    { id: 'sport-8', word: 'Fitness', translation: 'Fitness', pronunciation: 'FIT-nes', deck: 'sport', ...freshCard() },
    { id: 'sport-9', word: 'Gewichte', translation: 'Weights', pronunciation: 'guh-VIKH', deck: 'sport', ...freshCard() },
    { id: 'sport-10', word: 'Trainer', translation: 'Coach', pronunciation: 'TRAY-ner', deck: 'sport', ...freshCard() },
    { id: 'sport-11', word: 'Spiel', translation: 'Game', pronunciation: 'SHPEEL', deck: 'sport', ...freshCard() },
    { id: 'sport-12', word: 'Tor', translation: 'Goal', pronunciation: 'TOR', deck: 'sport', ...freshCard() },
    { id: 'sport-13', word: 'Punkte', translation: 'Points', pronunciation: 'POONK-tuh', deck: 'sport', ...freshCard() },
    { id: 'sport-14', word: 'Mannschaft', translation: 'Team', pronunciation: 'MAHN-shaft', deck: 'sport', ...freshCard() },
    { id: 'sport-15', word: 'Sieger', translation: 'Winner', pronunciation: 'ZEE-ger', deck: 'sport', ...freshCard() },
    { id: 'sport-16', word: 'Wettkampf', translation: 'Competition', pronunciation: 'VET-kahmpf', deck: 'sport', ...freshCard() },
    { id: 'sport-17', word: 'Stadion', translation: 'Stadium', pronunciation: 'SHTAH-dee', deck: 'sport', ...freshCard() },
    { id: 'sport-18', word: 'Zuschauer', translation: 'Spectator', pronunciation: 'TSOO-shaw', deck: 'sport', ...freshCard() },
    { id: 'sport-19', word: 'Schiedsrichter', translation: 'Referee', pronunciation: 'SHEETS-rik', deck: 'sport', ...freshCard() },
    { id: 'sport-20', word: 'Medaille', translation: 'Medal', pronunciation: 'muh-DAHL', deck: 'sport', ...freshCard() },
    { id: 'sport-21', word: 'Rekord', translation: 'Record', pronunciation: 'ruh-KOR', deck: 'sport', ...freshCard() },
    { id: 'sport-22', word: 'Training', translation: 'Training', pronunciation: 'TRAY-ning', deck: 'sport', ...freshCard() },
    { id: 'sport-23', word: 'Trikot', translation: 'Jersey', pronunciation: 'tree-KOH', deck: 'sport', ...freshCard() },
    { id: 'sport-24', word: 'Schuh', translation: 'Shoe', pronunciation: 'SHOO', deck: 'sport', ...freshCard() },
    { id: 'sport-25', word: 'Ball', translation: 'Ball', pronunciation: 'BAHL', deck: 'sport', ...freshCard() },
  ],
  alltag: Array.from({ length: 50 }, (_, i) => ({
    id: `alltag-${i + 1}`,
    word: `Alltag ${i + 1}`,
    translation: `Daily ${i + 1}`,
    pronunciation: '',
    example: 'Beispiel',
    deck: 'alltag',
    ...freshCard(),
  })),
  familie: [
    { id: 'familie-1', word: 'Mutter', translation: 'Mother', pronunciation: 'MOOT-er', deck: 'familie', ...freshCard() },
    { id: 'familie-2', word: 'Vater', translation: 'Father', pronunciation: 'FAH-ter', deck: 'familie', ...freshCard() },
    { id: 'familie-3', word: 'Bruder', translation: 'Brother', pronunciation: 'BROO-der', deck: 'familie', ...freshCard() },
    { id: 'familie-4', word: 'Schwester', translation: 'Sister', pronunciation: 'SHVES-ter', deck: 'familie', ...freshCard() },
    { id: 'familie-5', word: 'Großmutter', translation: 'Grandmother', pronunciation: 'GROSS', deck: 'familie', ...freshCard() },
    { id: 'familie-6', word: 'Großvater', translation: 'Grandfather', pronunciation: 'GROSS-fah', deck: 'familie', ...freshCard() },
    { id: 'familie-7', word: 'Tante', translation: 'Aunt', pronunciation: 'TAHN-tuh', deck: 'familie', ...freshCard() },
    { id: 'familie-8', word: 'Onkel', translation: 'Uncle', pronunciation: 'OHN-kel', deck: 'familie', ...freshCard() },
    { id: 'familie-9', word: 'Cousin', translation: 'Cousin', pronunciation: 'koo-ZAN', deck: 'familie', ...freshCard() },
    { id: 'familie-10', word: 'Cousine', translation: 'Cousin', pronunciation: 'koo-ZEE', deck: 'familie', ...freshCard() },
    { id: 'familie-11', word: 'Ehemann', translation: 'Husband', pronunciation: 'AY-uh-mahn', deck: 'familie', ...freshCard() },
    { id: 'familie-12', word: 'Ehefrau', translation: 'Wife', pronunciation: 'AY-uh-frow', deck: 'familie', ...freshCard() },
    { id: 'familie-13', word: 'Sohn', translation: 'Son', pronunciation: 'ZOHN', deck: 'familie', ...freshCard() },
    { id: 'familie-14', word: 'Tochter', translation: 'Daughter', pronunciation: 'TOKH-ter', deck: 'familie', ...freshCard() },
    { id: 'familie-15', word: 'Eltern', translation: 'Parents', pronunciation: 'EL-tern', deck: 'familie', ...freshCard() },
    { id: 'familie-16', word: 'Geschwister', translation: 'Siblings', pronunciation: 'guh-SHVIS', deck: 'familie', ...freshCard() },
    { id: 'familie-17', word: 'Kind', translation: 'Child', pronunciation: 'KINT', deck: 'familie', ...freshCard() },
    { id: 'familie-18', word: 'Baby', translation: 'Baby', pronunciation: 'BAY-bee', deck: 'familie', ...freshCard() },
    { id: 'familie-19', word: 'Verwandter', translation: 'Relative', pronunciation: 'fer-VANDT', deck: 'familie', ...freshCard() },
    { id: 'familie-20', word: 'Familie', translation: 'Family', pronunciation: 'fah-MEE', deck: 'familie', ...freshCard() },
  ],
  gefuehle: Array.from({ length: 30 }, (_, i) => ({
    id: `gefuehle-${i + 1}`,
    word: `Gefühl ${i + 1}`,
    translation: `Feeling ${i + 1}`,
    pronunciation: '',
    example: 'Beispiel',
    deck: 'gefuehle',
    ...freshCard(),
  })),
  business: Array.from({ length: 40 }, (_, i) => ({
    id: `business-${i + 1}`,
    word: `Business ${i + 1}`,
    translation: `Business ${i + 1}`,
    pronunciation: '',
    example: 'Beispiel',
    deck: 'business',
    ...freshCard(),
  })),
  schule: Array.from({ length: 35 }, (_, i) => ({
    id: `schule-${i + 1}`,
    word: `Schule ${i + 1}`,
    translation: `School ${i + 1}`,
    pronunciation: '',
    example: 'Beispiel',
    deck: 'schule',
    ...freshCard(),
  })),
  technik: Array.from({ length: 30 }, (_, i) => ({
    id: `technik-${i + 1}`,
    word: `Technik ${i + 1}`,
    translation: `Tech ${i + 1}`,
    pronunciation: '',
    example: 'Beispiel',
    deck: 'technik',
    ...freshCard(),
  })),
}
